
services:

  db:
    container_name: postgres
    image: postgres
    init: true 
    build:
      dockerfile: Postgres/Dockerfile
      args:
       POSTGRES_USER: $POSTGRES_USER
       POSTGRES_PASSWORD: $POSTGRES_PASSWORD
       POSTGRES_DB: $POSTGRES_DB
    env_file: .env
    restart: always
    expose:
      - "5432:5432"

  server:
    container_name: server
    image: server
    init: true
    networks:
      - ft_transcendence
    build:
      dockerfile: nginx/Dockerfile
    env_file: .env
    restart: on-failure
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - server:/django

#ou placer le dossier montee dans le docker /django docker 

volumes:
  server:
    name: server
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/lciullo/ft_transcendence/django
#device : dossier dans lequel il y l'installation django sur machine hote 

networks:
  ft_transcendence:
