
services:

  db:
    container_name: postgres
    image: postgres
    build:
      dockerfile: Postgres/Dockerfile
      args:
       POSTGRES_USER: $POSTGRES_USER
       POSTGRES_PASSWORD: $POSTGRES_PASSWORD
       POSTGRES_DB: $POSTGRES_DB
    env_file: .env
    restart: always
    expose:
      - "5432"


# services:
 
#   db:
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_PASSWORD: example
#     volumes:
# - pgdata:/var/lib/postgresql/data
 
# volumes:
#   pgdata:
 
#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080