
services:

  db:
    container_name: postgres
    image: postgres
    init: true 
    build:
      dockerfile: docker/Postgres/Dockerfile
      args:
       POSTGRES_USER: $POSTGRES_USER
       POSTGRES_PASSWORD: $POSTGRES_PASSWORD
       POSTGRES_DB: $POSTGRES_DB
    env_file: .env
    restart: always
    expose:
      - "5432:5432"

  server:
    container_name: server
    image: server
    init: true
    networks:
      - ft_transcendence
    build:
      dockerfile: docker/nginx/Dockerfile
    command: python /backend/ft_transcendence/manage.py runserver 0.0.0.0:8000
    env_file: .env
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - server:/backend

#ou placer le dossier montee dans le docker /backend docker 

volumes:
  server:
    name: server
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/lciullo/ft_transcendence/backend
#device : dossier dans lequel il y l'installation django sur machine hote 

networks:
  ft_transcendence:
