services:
  db:
    container_name: postgres
    init: true 
    networks:
      - ft_transcendence
    build:
      dockerfile: database/Dockerfile
    env_file: .env
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_HOST} -h localhost"]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data

  
  server:
    container_name: server
    init: true
    networks:
      - ft_transcendence
    build:
      dockerfile: backend/Dockerfile
    env_file: .env
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/:/backend

#ou placer le dossier montee dans le docker /backend docker 
#changer de path
  # adminer:
  #   image: adminer:4.8.1
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db
  #   restart: on-failure

volumes:
  server:
    name: server
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $PWD/backend
  postgres_data:
    name: postgres_data



networks:
  ft_transcendence:
